<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AiGisConverter.Gis.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AiGisConverter.Gis\AiGisConverter.Gis.csproj" />
  </ItemGroup>

</Project>
