using AiGisConverter.Domain.Entities.Project;
using AiGisConverter.Domain.Entities.QaQc;
using AiGisConverter.Domain.Enums;

namespace AiGisConverter.Application.Dtos;

/// <summary>A project, flattened for display.</summary>
/// <param name="Id">The project identifier, as text.</param>
/// <param name="Name">The project name.</param>
/// <param name="Description">The optional description.</param>
/// <param name="JobCount">How many drawings the project holds.</param>
/// <param name="TargetCrs">The output coordinate system identifier.</param>
/// <param name="ExportFormats">The formats the project writes.</param>
/// <param name="CreatedAtUtc">When the project was created.</param>
/// <param name="ModifiedAtUtc">When it was last changed.</param>
public sealed record ProjectSummaryDto(
    string Id,
    string Name,
    string? Description,
    int JobCount,
    string TargetCrs,
    IReadOnlyList<string> ExportFormats,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? ModifiedAtUtc);

/// <summary>A run, flattened for display.</summary>
/// <param name="Id">The run identifier, as text.</param>
/// <param name="Status">The terminal or current status.</param>
/// <param name="StartedAtUtc">When the run started.</param>
/// <param name="Duration">How long it took, when finished.</param>
/// <param name="ElementsRead">Source elements read.</param>
/// <param name="FeaturesWritten">Features written.</param>
/// <param name="HighestSeverity">The most serious finding.</param>
/// <param name="IssueCount">How many findings there were.</param>
/// <param name="CoordinateSystem">The system the output is in.</param>
/// <param name="CrsSource">How that system was determined.</param>
/// <param name="FailureReason">Why the run failed, when it did.</param>
/// <param name="OutputPaths">The files written.</param>
public sealed record RunSummaryDto(
    string Id,
    ConversionStatus Status,
    DateTimeOffset? StartedAtUtc,
    TimeSpan? Duration,
    int ElementsRead,
    int FeaturesWritten,
    IssueSeverity HighestSeverity,
    int IssueCount,
    string? CoordinateSystem,
    CrsDetectionSource CrsSource,
    string? FailureReason,
    IReadOnlyList<string> OutputPaths);

/// <summary>A validation finding, flattened for display.</summary>
/// <param name="Severity">How serious it is.</param>
/// <param name="Category">What kind of thing it concerns.</param>
/// <param name="Code">The stable rule code.</param>
/// <param name="Message">The description.</param>
/// <param name="Layer">The layer concerned, when any.</param>
/// <param name="FeatureId">The feature concerned, when any.</param>
/// <param name="FieldName">The field concerned, when any.</param>
/// <param name="LocationX">Map X, when the finding has a location.</param>
/// <param name="LocationY">Map Y, when the finding has a location.</param>
/// <param name="Remediation">How to fix it, when the rule can say.</param>
public sealed record ValidationIssueDto(
    IssueSeverity Severity,
    IssueCategory Category,
    string Code,
    string Message,
    string? Layer,
    string? FeatureId,
    string? FieldName,
    double? LocationX,
    double? LocationY,
    string? Remediation);

/// <summary>
/// Flattens domain aggregates for the user interface.
/// </summary>
/// <remarks>
/// <para>
/// Hand-written rather than generated by a mapping library. There are three shapes, the mapping is
/// obvious, and a convention-based mapper would silently produce a null the day a property is
/// renamed &#8212; whereas this stops compiling.
/// </para>
/// <para>
/// The direction is one-way. Nothing constructs an aggregate from a DTO: the domain's factory
/// methods enforce invariants a DTO cannot, and a mapper that bypassed them would be a hole in
/// every rule the domain has.
/// </para>
/// </remarks>
public static class ConversionMapper
{
    /// <summary>Flattens a project.</summary>
    /// <param name="project">The project to flatten.</param>
    /// <returns>The summary.</returns>
    public static ProjectSummaryDto ToSummary(ConversionProject project)
    {
        ArgumentNullException.ThrowIfNull(project);

        return new ProjectSummaryDto(
            project.Id.ToString(),
            project.Name,
            project.Description,
            project.Jobs.Count,
            project.Settings.TargetCoordinateSystem.Identifier,
            [.. project.Settings.ExportFormats.Select(static format => format.ToString())],
            project.CreatedAtUtc,
            project.ModifiedAtUtc);
    }

    /// <summary>Flattens a run.</summary>
    /// <param name="run">The run to flatten.</param>
    /// <returns>The summary.</returns>
    public static RunSummaryDto ToSummary(ConversionRun run)
    {
        ArgumentNullException.ThrowIfNull(run);

        return new RunSummaryDto(
            run.Id.ToString(),
            run.Status,
            run.StartedAtUtc,
            run.Duration,
            run.ElementsRead,
            run.FeaturesWritten,
            run.HighestSeverity,
            run.IssueCount,
            run.ResolvedCoordinateSystem?.Identifier,
            run.CrsSource,
            run.FailureReason,
            run.OutputPaths);
    }

    /// <summary>Flattens a finding.</summary>
    /// <param name="issue">The finding to flatten.</param>
    /// <returns>The flattened finding.</returns>
    public static ValidationIssueDto ToDto(ValidationIssue issue)
    {
        ArgumentNullException.ThrowIfNull(issue);

        return new ValidationIssueDto(
            issue.Severity,
            issue.Category,
            issue.Code,
            issue.Message,
            issue.Layer?.Value,
            issue.FeatureId,
            issue.FieldName,
            issue.LocationX,
            issue.LocationY,
            issue.Remediation);
    }

    /// <summary>Flattens every finding in a report, most serious first.</summary>
    /// <param name="report">The report to flatten.</param>
    /// <returns>The flattened findings.</returns>
    public static IReadOnlyList<ValidationIssueDto> ToDtos(ValidationReport report)
    {
        ArgumentNullException.ThrowIfNull(report);

        return [.. report.AtOrAbove(IssueSeverity.Information).Select(ToDto)];
    }
}
