<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AiGisConverter.Business.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AiGisConverter.Business\AiGisConverter.Business.csproj" />
  </ItemGroup>

</Project>
